[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
z3 = {version="0.12", features = ["static-link-z3"]}
ndarray-linalg = { version = "0.16", features = ["openblas-system"] }
ndarray = "0.15.6"
